---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-vault
spec:
  selector:
    matchLabels:
      app: cloudflared
  replicas: 1
  template:
    metadata:
      labels:
        app: cloudflared
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:2022.3.0
        args:
        - tunnel
        - --config
        - /etc/cloudflared/config/config.yaml
        - run
        volumeMounts:
        - name: config
          mountPath: /etc/cloudflared/config
          readOnly: true
        - name: creds
          mountPath: /etc/cloudflared/creds
          readOnly: true
      volumes:
      - name: creds
        secret:
          secretName: vault-credentials
      - name: config
        configMap:
          name: cloudflared-vault
          items:
          - key: config.yaml
            path: config.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-vault
data:
  config.yaml: |
    tunnel: {{ .Values.cloudflared.tunnelname }}
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000

    ingress:
    - hostname: {{ .Values.cloudflared.hostname }}
      service: http://vault-vault.default.svc.cluster.local:8200

    - service: http_status:404