apiVersion: apps/v1
kind: Deployment
metadata:
    name: app-deployment
    labels:
    app: reminder-app
spec:
    replicas: 1
    selector:
        matchLabels:
            app: reminder-app
    template:
        metadata:
            labels:
                app: reminder-app
        spec:
            containers:
                - name: reminder-app
                  image: reminder-app:latest
                  ports:
                      - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
    name: app-service
spec:
    selector:
        app: reminder-app
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
    type: NodePort
