apiVersion: apps/v1
kind: Deployment
metadata:
    name: app-deployment
    labels:
        app: reminder-app
spec:
    replicas: 1
    selector:
        matchLabels:
            app: reminder-app
    template:
        metadata:
            labels:
                app: reminder-app
        spec:
            containers:
                - name: reminder-app
                  image: thybevb/reminder-app:latest
                  ports:
                      - containerPort: 3000
                  env:
                      - name: MONGO_URI
                        value: "mongodb://mongo-service:27017/reminders"
---
apiVersion: v1
kind: Service
metadata:
    name: app-service
spec:
    selector:
        app: reminder-app
    ports:
        - protocol: TCP
          port: 3000
          targetPort: 3000
    #type: LoadBalancer # In nginx wordt reverse proxy ingesteld, dus api kan in principe afgeschermd worden
    type: ClusterIP
