apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deployment
    labels:
        app: nginx
spec:
    replicas: 1
    selector:
        matchLabels:
            app: nginx
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
                - name: nginx
                  image: nginx:latest
                  ports:
                      - containerPort: 80
                  volumeMounts:
                      - name: website-files
                        mountPath: /usr/share/nginx/html
                      - name: nginx-config
                        mountPath: /etc/nginx/conf.d/default.conf
                        subPath: default.conf
            volumes:
            - name: website-files
              configMap:
                name: reminder-app-frontend
            - name: nginx-config
              configMap:
                name: reminder-app-nginxconfig
---
apiVersion: v1
kind: Service
metadata:
    name: nginx-service
spec:
    selector:
        app: nginx
    ports:
        - protocol: TCP
          port: 80
          targetPort: 80
    type: LoadBalancer
