apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app
  labels:
    app: {{ .Release.Name }}-app
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-app 
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-app 
    spec:
      containers:
      - name: app
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: "mongodb://{{ .Release.Name }}-mongo-service:27017/reminders"
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-app-service
spec:
  selector:
    app: {{ .Release.Name }}-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: {{ .Values.service.type }}
