apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-mongo
  labels:
    app: {{ .Release.Name }}-mongo
spec:
  replicas: {{ .Values.mongo.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-mongo
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-mongo
    spec:
      containers:
      - name: mongo
        image: {{ .Values.mongo.image }}
        args: ["--bind_ip_all"]
        ports:
        - containerPort: {{ .Values.mongo.service.port }}
        #env:
        #- name: MONGO_INITDB_ROOT_USERNAME
        #  valueFrom:
        #    secretKeyRef:
        #      name: mongo-creds
        #      key: username
        #- name: MONGO_INITDB_ROOT_PASSWORD
        #  valueFrom:
        #    secretKeyRef:
        #      name: mongo-creds
        #      key: password
        volumeMounts:
        - mountPath: /data/db
          name: mongo-storage
      volumes:
      - name: mongo-storage
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-mongo-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mongo-service
spec:
  selector:
    app: {{ .Release.Name }}-mongo
  ports:
  - protocol: TCP
    port: {{ .Values.mongo.service.port }}
    targetPort: {{ .Values.mongo.service.port }}
  type: {{ .Values.mongo.service.type }}