replicaCount: 1

image:
  repository: thybevb/reminder-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

nginx:
  replicas: 1
  image: nginx:latest
  service:
    type: LoadBalancer
    port: 80
    annotations:
      service.beta.kubernetes.io/oci-load-balancer-subnet1: "ocid1.subnet.oc1.eu-amsterdam-1.aaaaaaaalctlggapgbkmwxqny4dmlwgxdz75mrqecpfxld6nhcccc4ma66fa"

resources:
  limits:
    cpu: 1024m
    memory: 2048Mi
  requests:
    cpu: 1024m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

mongo:
  image: mongo:6.0
  pvc:
    storage: 2Gi
