node:
  replicaCount: 1
  service:
    type: ClusterIP
    port: 3000
  image:
    repository: thybevb/reminder-app
    tag: latest
    pullPolicy: Always

nginx:
  replicaCount: 1
  image: nginx:latest
  service:
    type: LoadBalancer
    port: 80
    annotations:
      service.beta.kubernetes.io/oci-load-balancer-subnet1: "ocid1.subnet.oc1.eu-amsterdam-1.aaaaaaaa5rerinqmfwchvob4xhd7hfwos54644kid3ijiie33pcvfpumvatq"
      #service.beta.kubernetes.io/oci-load-balancer-subnet2: "" Als verschillende regio's gekozen worden ocid1.subnet.oc1.eu-amsterdam-1.aaaaaaaa5rerinqmfwchvob4xhd7hfwos54644kid3ijiie33pcvfpumvatq

resources:
  limits:
    cpu: 1024m
    memory: 2048Mi
  requests:
    cpu: 1024m
    memory: 64Mi

nodeSelector: {}

tolerations: []

affinity: {}

mongo:
  image: mongo:6.0
  replicaCount: 1
  pvc:
    storage: 2Gi
  service:
    type: ClusterIP
    port: 27017
